### ISSUE TITLE
Warn if `formData` hash values are not strings, to prevent `source.on is not a function`

### ISSUE THREAD

**Issue by nhooey** [form-data/form-data#321] opened 2017-02-04 20:37 UTC
In request/request#1495, the example code gets an error like `source.on is not a function` because one of the values in the `formData` has for a `request` or `request-promise` options hash is not a string.

The `form-data` module should detect this error and tell the user to ensure all `formdata` hash values are strings, or `writeStreams`, or whatever else is valid.

**Comment by alexindigo** [comment] 2017-06-10 22:46
Yeah, looks like legit issue. Do you mind to create a PR? Thank you

**Comment by nhooey** [comment] 2017-06-13 01:03
@alexindigo That was four months ago. I'm not using the library anymore...

**Comment by alexindigo** [comment] 2017-06-13 01:11
Ok. I'll close this issue then. :) Thanks.

**Comment by nhooey** [comment] 2017-06-13 01:26
Why would you close an issue without a solution?

**Comment by alexindigo** [comment] 2017-06-13 01:40
You said, you're no longer interested in this issue. So it was logical to close it.
Please let me know if/when you want to get back to it. Thank you.

**Comment by nhooey** [comment] 2017-06-13 03:39
I meant that I can't really make a pull request for it.

It's still an issue potentially to a lot of people, even if they don't complain about it. It's an instance where the code doesn't check its inputs, which is a defect.

**Comment by nhooey** [comment] 2017-06-13 03:42
I'd suggest leaving it open so we can track the defect.

**Comment by alexindigo** [comment] 2017-06-13 05:22
Ok.

**Comment by nhooey** [comment] 2017-06-13 06:52
Thanks @alexindigo!

**Comment by DylanPiercey** [comment] 2017-07-15 02:03
I'll take a look at this when we do https://github.com/form-data/form-data/issues/137.

**Comment by DylanPiercey** [comment] 2017-07-15 03:02
Closing as a duplicate of https://github.com/form-data/form-data/issues/137.
Work is being done in https://github.com/form-data/form-data/pull/362.

**Closed by DylanPiercey** 2017-07-15 03:02 UTC

**Comment by DylanPiercey** [comment] 2017-07-15 03:03
Also, specifically for converting objects to use formdata syntax see [q-flat](https://github.com/DylanPiercey/q-flat).
