### ISSUE TITLE
null check inside append()

### ISSUE THREAD

**Issue by mavrick** [form-data/form-data#147] opened 2015-10-06 14:41 UTC
Hey,

Can we get a null check or an undefined check on the value param inside the `FormData.prototype.append` function please?

`/lib/form_data.js:25`

``` javascript
if (typeof value == undefined)
{
    this._error(new Error('Undefined values are not supported.'));
    return;
}
```

Otherwise you end up with an uncaught exception inside of `FormData.prototype._multiPartHeader` on line 151

Cheers

**Comment by DylanPiercey** [comment] 2015-12-06 00:01
@mavrik in @2.0 we are going to `String` all values in am effort to make the api symmetrical to the browser api which will fix this issue.

**Comment by DylanPiercey** [comment] 2016-08-23 07:07
@alexindigo I think we should update this sooner than later, what's your thoughts?

**Comment by magicdawn** [comment] 2016-09-10 06:54
how is this going on ?

**Comment by DylanPiercey** [comment] 2017-07-15 01:49
Going to close this as a duplicate of https://github.com/form-data/form-data/issues/137.

Hope to tackle this soon.

**Closed by DylanPiercey** 2017-07-15 01:49 UTC
