### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by chrisabrams** [form-data/form-data#336] opened 2017-03-23 22:18 UTC
What in the world am I doing wrong to cause this to be undefined? https://github.com/form-data/form-data/blob/03444d21961a7a44cdc2eae11ee3630f6969023d/lib/form_data.js#L217

I'm assuming it is referring to `value`

**Comment by MarkHerhold** [comment] 2017-04-07 18:07
I think you need to use `form` instead of `formData` as the object key. I ran into this using the `request-promise` module.

**Comment by alexindigo** [comment] 2017-04-07 18:28
@chrisabrams Do you have code snippet that triggers the error? And would be nice to see the error too. Thanks.

**Comment by jordpo** [comment] 2017-05-11 22:33
@alexindigo I'm also running into the issue. I am also using `request-promise` and I'm trying to send a local file. 
```
          var formData = {
            apiKey: apiKey,
            version: revisionKey,
            minifiedUrl: jsFilePath,
            sourceMap: fs.createReadStream(mapFilePath),
          };
          var promise = request({
            uri: 'https://upload.bugsnag.com/',
            method: 'POST',
            formData: formData,
          });

```

I used a debugger and can confirm that the file is being ready properly using `fs.statSync(mapFilePath)`.

@MarkHerhold I still think you need to use `formData` - all of the other examples I see out there use it.

**Comment by jordpo** [comment] 2017-05-12 15:58
What I noticed is that the issue comes up if any of the properties that you are setting on the form data has a value of undefined. Guarding against that fixed the issue for me.

**Comment by ronaldpabilonia** [comment] 2017-05-13 14:25
Hello, I've ran into this issue as well and after seeing @jordpo 's answer, I checked to see if I was leaving any undefines. Turns out I'm only appending two keys and values and pretty sure it's not undefined. So I'm still wondering why I get this error. I'm sending an ID string and a file:

```javascript
        var requestLib = require('request');
        var FormData = require('form-data');
	var fs = require('fs');
	var form = new FormData();

	form.append('pid', params.pid);
	form.append('deliveryAttachment', fs.createReadStream(params.deliveryAttachment[0].path));

	requestLib({
		url: url,
		method: "POST",
		headers: {
		     'Content-Type': 'multipart/form-data'
		},	
		formData: form
	},function (error, response, body){ 
              ...
        });
```

**Comment by ronaldpabilonia** [comment] 2017-05-13 14:45
Quick update, I was able to fix my issue by just directly creating an object instead of using the FormData module. I just followed @jordpo 's example and the file was uploaded.

```javascript
        var data = {
		pid: params.pid,
		deliveryAttachment: fs.createReadStream(params.deliveryAttachment[0].path)
	};	
	requestLib({
		url: url,
		method: "POST",
		headers: {
			'Content-Type': 'multipart/form-data'
		},	
		jar: getJar(),
		formData: data
	},function (error, response, body){
              ...
        });
```

**Comment by jordpo** [comment] 2017-05-13 15:02
@ronaldpabilonia awesome. Yeah from the examples I've played around with, when using the form-data module directly, it's best to call submit on it vs adding it as a value in your request.

```
formData.submit(url, function(error, result) {
      if (error) {
        reject(error);
      }
      result.resume();

      result.on('end', function() {
        resolve();
      });
    });
```

I wonder if the request library is expecting an object vs a FormData instance and when it tries to instantiate another instance the key value pairs are undefined.

**Comment by senica** [comment] 2017-06-20 22:14
Also happened to me with `NULL` values, not just `undefined`.

**Comment by SimonSchick** [comment] 2017-07-05 17:06
`null` and `undefined` should probably be treated as empty strings.

**Comment by DylanPiercey** [comment] 2017-07-15 01:46
Closing as duplicate of https://github.com/form-data/form-data/issues/137
I hope to tackle this soon.

**Closed by DylanPiercey** 2017-07-15 01:46 UTC
